# http://about.travis-ci.org/docs/user/gui-and-headless-browsers/
language: node_js

cache:
  - apt
  - npm
  
matrix:
  fast_finish: true
  
services: mongodb

before_install:
  - export DISPLAY=:99.0
  - sh -e /etc/init.d/xvfb start
  - /sbin/start-stop-daemon --start --quiet --pidfile /tmp/custom_xvfb_99.pid --make-pidfile --background --exec /usr/bin/Xvfb -- :99 -ac -screen 0 1280x1024x24

  
script:
  - chmod u+x start.sh
  - ./start.sh
  

